### ISSUE TITLE
Surface temperature and Shallow Mixed Ocean Layer

### ISSUE THREAD

**Issue by lsoucasse** [FormingWorlds/PROTEUS#148]
Before an atmosphere calculation, a specific surface temperature is calculated if the shallow_ocean_layer option is triggered (l.48 script `wrapper_atmosphere.py`).

But when using Janus, the surface temperature is always overwritten to T_magma (couple of lines after). When using Agni, it is only overwritten at first iteration, which make more sense. I guess it should be the same for Janus. Could you clarify ths @nichollsh or @timlichtenberg ?

**Comment by nichollsh** [comment]
The second case makes the most sense to me, although in the JANUS case it should still be set to T_magma in the first time-step since there's no time over which to integrate the mixed layer's heat capacity.

I haven't actually used this shallow mixed layer scheme at all, although it is useful to keep it around for potential comparison with other codes and how they handle their surface boundary conditions. We should think about testing it at some point.

**Comment by lsoucasse** [comment]
Close this comment. Addressed in janus_wrapper branch attached to issue #120.
