### ISSUE TITLE
Mors as sub-module

### ISSUE THREAD

**Issue by timlichtenberg** [FormingWorlds/PROTEUS#39]
- https://github.com/ColinPhilipJohnstone/Mors
- self-consistent model for evolutionary tracks for stellar rotation, X-ray, EUV, and Ly-alpha emission for stars with masses between 0.1 and 1.25 Msun

**Comment by nichollsh** [comment]
Mors allows us to calculate the luminosities L_n of a star for different ages and rotation rates. These L_n are for different spectral bands: X-ray, EUV1, EUV2, EUV3, bolometric. Having just L_bol is helpful for AEOLUS alone, but if we want to provide a spectrum to VULCAN we need to think about how to generate a spectrum from these.

Since presumably we'll know the spectrum of the star in its current state (or that of a similar star), we could use the past L_n to scale up/down the different bands over time. This seems fairly reasonable as it captures the XUV evolution in such a way that the total energy is correct, although we'd likely be over- and under-estimating certain spectral features.

**Comment by nichollsh** [comment]
In that case, it might be reasonable to use the luminosity-scaling approach I outlined above. It should be pretty easy to set that up with spectra from the following websites:
* https://phoenix.astro.physik.uni-goettingen.de/?page_id=15
* https://archive.stsci.edu/prepds/muscles/
* https://vpl.astro.washington.edu/spectra/stellar/other_stars.htm

We could at least use Sarah's M-star evolution model to validate the L-scaling approach.

**Comment by nichollsh** [comment]
I've given this approach a go. It seems to work quite well so far, and probably well enough for our purposes. It'd be good to validate it against some other model/approach, and I wouldn't go as far to trust it in generating stellar spectra for synthetic observations.

I've also added a tool for automatically downloading/parsing spectra from the MUSCLES/VPL websites. At runtime, spectra are saved to `output/` so that they can be debugged and used by submodules.

See the example plot below, for GJ1132. Updates are in the [Mors branch](https://github.com/FormingWorlds/PROTEUS/tree/mors).

<img width="761" alt="image" src="https://github.com/FormingWorlds/PROTEUS/assets/32022679/e9ffb4fd-8359-4439-840d-88eea7ddfa22">

**Comment by timlichtenberg** [comment]
Very nice! :-) If this is automated enough, we could even consider generating an appropriate spectral file during runtime for SOCRATES. The insertion of the stellar spectrum is the last step in creating spectral files for SOCRATES. The file `/AEOLUS/spectral_files/sp_b318_HITRAN_a16/sp_b318_HITRAN_a16_no_spectrum_k` is essentially a vanilla version of the spectral file, inserting the stellar spectrum takes ~ a second.
