### ISSUE TITLE
SPIDER execution time

### ISSUE THREAD

**Issue by nichollsh** [FormingWorlds/PROTEUS#81]
SPIDER is usually very fast, but in some circumstances it can be very slow. I don't know why exactly this is, but something is forcing SPIDER to take very small sub-steps in order to sufficiently resolve the time-evolution of the interior.

This can mean that a single SPIDER call takes >1 hour of runtime, while in the majority of cases it only takes a few seconds.

I am sure this could be alleviated by loosening (increasing) the solver tolerance, but it would be worthwhile investigating what exactly is that cause of this.

**Comment by nichollsh** [comment]
This is probably linked to Issue #62.

**Comment by djbower** [comment]
This is most likely because some region of the interior has become sub-adiabatic, so now the heat transfer is very slow (because convection is not occurring, so energy is only transported by conduction and maybe gravitational separation). Another option is that a surface lid is being formed and then destroyed, which again drives down the time step.  Both of these scenarios will be easier to probe in more detail with pyspider.

**Comment by nichollsh** [comment]
Thanks for the information. It does seem that this scenario is more likely to occur when the melt fraction becomes small, so a surface lid is being formed/destroyed repeatedly. I've found that increasing the grid resolution can help in those cases, so maybe it will help prevent these long runtimes too. 

Looking forward to pyspider :)

**Comment by djbower** [comment]
Yes, increasing the resolution can help, although in practice it only delays the inevitable (a lid will form eventually).  In Bower et al. (2022) the fractional crystallization cases are relatively well-behaved because the flushing of energy (heat) towards the surface keeps the surface hotter for longer, thus mitigating surface lid formation.

**Comment by nichollsh** [comment]
Closing this is no longer an issue. 

Increasing the resolution and using the dynamic tolerances solves this for the most part. Additionally, we aim to move development to Aragog going forward.
